spring:
  profiles:
    active: local

  thymeleaf.cache: false

  devtools:
    livereload.enabled: true
    restart.enabled: true

  jpa:
    hibernate.ddl-auto: update
    database: mysql
    show-sql: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/wootecobook?serverTimezone=UTC
    username: zzinbros
    password: 1234

---

spring:
  profiles: test

  thymeleaf.cache: false

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

debug: true

---

spring:
  profiles: deploy

  jpa:
    hibernate.ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/wootecobook?serverTimezone=UTC
    username: zzinbros
    password: 1234

  logging:
    level:
      root: ERROR
      com.woowacourse.zzinbros: WARN
      org.springframework: WARN
      org.hibernate: INFO

  output:
    ansi:
      enabled: detect
